[package]
name = "esvc-core"
version = "0.0.0"
edition = "2021"
license = "Apache-2.0 WITH LLVM-exception"

[dependencies]
base64 = "0.13"
bincode = "1.3"
blake2 = "0.10"
rayon = "1.5"
serde_with = "1.11"
thiserror = "1.0"
uuid = "0.8"

[dependencies.anyhow]
version = "1.0"
features = ["backtrace"]

[dependencies.serde]
version = "1.0"
features = ["derive"]

[dependencies.wasmtime]
version = "0.33"
default-features = false
features = ["cranelift", "parallel-compilation"]
