[package]
name = "esvc-core"
version = "0.0.0"
edition = "2021"
license = "Apache-2.0 WITH LLVM-exception"

[dependencies]
bincode = "1.3"
blake2 = "0.10"
serde_with = "1.11"
thiserror = "1.0"
uuid = "0.8"
base64 = "0.13.0"

[dependencies.serde]
version = "1.0"
features = ["derive"]
